### ISSUE TITLE
Bug — Subsemester selection doesn't always show up

### ISSUE THREAD

**Issue by marchdan** [YACS-RCOS/yacs.n#418] opened 2021-03-09 17:42 UTC
**Describe the bug**
Subsemester filter does not show up when Summer is navigated to from the footer if not default

**To Reproduce**
1. Go to yacs.cs.rpi.edu
2. Click on navigate to SUMMER 2021 using the site footer
3. Look for sub-sememester course filters

**Expected behavior**
Course filter and schedule filter should show up for sub-semesters

**Screenshots**
![Screenshot 2021-03-09 123927](https://user-images.githubusercontent.com/35609442/110514017-d7fc7280-80d4-11eb-9587-d0e62f639fea.png)

**Additional context**
I believe this to be a Vuex issue and may be fixed by pending PR.

**Comment by RichtXO** [comment] 2021-03-09 17:52
Update: This bug was caused by someone who uploaded the wrong version of the courses CSV :) (my bad)

**Comment by 123joshuawu** [comment] 2021-03-29 00:21
Should be fixed by #425?

**Closed** 2021-03-30 02:44 UTC
Labels: bug
